[2023-11-23T19:18:03.805+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_postgres_table manual__2023-11-23T19:18:02.644100+00:00 [queued]>
[2023-11-23T19:18:03.813+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_operator.create_postgres_table manual__2023-11-23T19:18:02.644100+00:00 [queued]>
[2023-11-23T19:18:03.813+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 6
[2023-11-23T19:18:03.824+0000] {taskinstance.py:1382} INFO - Executing <Task(PostgresOperator): create_postgres_table> on 2023-11-23 19:18:02.644100+00:00
[2023-11-23T19:18:03.829+0000] {standard_task_runner.py:57} INFO - Started process 305 to run task
[2023-11-23T19:18:03.833+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_operator', 'create_postgres_table', 'manual__2023-11-23T19:18:02.644100+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgres_operator.py', '--cfg-path', '/tmp/tmpmdla04hz']
[2023-11-23T19:18:03.836+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask create_postgres_table
[2023-11-23T19:18:03.893+0000] {task_command.py:416} INFO - Running <TaskInstance: dag_with_postgres_operator.create_postgres_table manual__2023-11-23T19:18:02.644100+00:00 [running]> on host e7b0b9311e50
[2023-11-23T19:18:03.985+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='harsha' AIRFLOW_CTX_DAG_ID='dag_with_postgres_operator' AIRFLOW_CTX_TASK_ID='create_postgres_table' AIRFLOW_CTX_EXECUTION_DATE='2023-11-23T19:18:02.644100+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-23T19:18:02.644100+00:00'
[2023-11-23T19:18:03.986+0000] {sql.py:274} INFO - Executing: 
            CREATE TABLE IF NOT EXISTS dag_runs (
            dt date ,
            dag_id character varying,
            primary key (dt, dag_id))
            
[2023-11-23T19:18:03.997+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-11-23T19:18:04.014+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-11-23T19:18:12.022+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 385, in run
    with closing(self.get_conn()) as conn:
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/postgres/hooks/postgres.py", line 155, in get_conn
    self.conn = psycopg2.connect(**conn_args)
  File "/home/airflow/.local/lib/python3.8/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "host.docker.local" to address: Temporary failure in name resolution

[2023-11-23T19:18:12.050+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_operator, task_id=create_postgres_table, execution_date=20231123T191802, start_date=20231123T191803, end_date=20231123T191812
[2023-11-23T19:18:12.069+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task create_postgres_table (could not translate host name "host.docker.local" to address: Temporary failure in name resolution
; 305)
[2023-11-23T19:18:12.114+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-23T19:18:12.132+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
